version: '3.8'

services:
  web:
    image: e0mru/wwbbru-web
    ports:
      - "8000:8000"
    volumes:
      - ./media:/code/media
      - ./db.sqlite3:/code/db.sqlite3
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
