# Generated by Django 4.0.4 on 2022-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
