# Generated by Django 4.0.4 on 2022-07-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_project_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['rating']},
        ),
    ]
