# Generated by Django 4.0.4 on 2022-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
