# Generated by Django 4.0.4 on 2022-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_project_options_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
