# Generated by Django 4.0.4 on 2022-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='album',
        ),
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
