# Generated by Django 4.0.4 on 2022-08-02 11:45

from django.db import migrations, models
import django.db.models.deletion
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_project_created_at_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='рейтинг (чем больше тем выше в выдаче)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='#Тэги'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=todo.models.id_path)),
                ('prj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
