# Generated by Django 4.0.4 on 2022-08-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_project_rating_alter_project_tags_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
