# Generated by Django 4.0.4 on 2022-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_comment_alter_project_photo_alter_project_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public',
            field=models.BooleanField(blank=True, null=True, verbose_name='Опубликован'),
        ),
    ]
