# Generated by Django 4.0.4 on 2022-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_comment_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
