# Generated by Django 4.0.4 on 2022-08-04 16:25

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_comment_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=todo.models.id_path),
        ),
    ]
