# Generated by Django 4.0.4 on 2022-09-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
    ]
