# Generated by Django 4.0.4 on 2022-09-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_remove_project_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
