# Generated by Django 4.0.4 on 2022-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_delete_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='album',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
