# Generated by Django 4.0.4 on 2022-09-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_project_album_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='album',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
