# Generated by Django 4.1.5 on 2024-03-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_alter_project_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
